# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.3'
services:
  peopleflow-app:
    image: peopleflow
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 127.0.0.1:8081:8081
